apiVersion: apps/v1
kind: Deployment
metadata:
  name: spacefunk-deployment
  namespace: spacefunk
spec:
  selector:
    matchLabels:
      app: spacefunk-deployment
  template:
    metadata:
      labels:
        app: spacefunk-deployment
    spec:
      containers:
      - name: spacefunk-deployment
        image: dancastroofc/spacefunk:v1
        # env:
        # - name: CLIENT_ID
        #   valueFrom:
        #     secretKeyRef:
        #       name: spacefunk-secret
        #       key: CLIENT_ID
        # - name: TOKEN
        #   valueFrom:
        #     secretKeyRef:
        #       name: spacefunk-secret
        #       key: TOKEN
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spacefunk-service
  namespace: spacefunk
spec:
  selector:
    app: spacefunk-deployment
  ports:
  - port: 8080
    targetPort: 8080
